version: '3.8'
services:
  elasticnetflow:
    build: .
    container_name: quickelasticnetflow
    ports:
      - "5601"   # Kibana
      - "${NETFLOW_PORT}:2055/udp" # Netflow/IPFIX UDP
    restart: unless-stopped
    init: true
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    # environment:
    #   - discovery.type=single-node
    #   - ES_JAVA_OPTS=-Xms1g -Xmx1g
    #   - ELASTIC_PASSWORD=changeme
    #   - ...

volumes:
  elastic_data:
